### ISSUE TITLE
[Proposal] Project rename

### ISSUE THREAD

**Issue by andreoav** [artesaos/guardian#10]
Given that already exists a project for Laravel with the same name and similar goal, we new ideas to rename the project.

* Guardian (keep the same)
* Unbroken **(1)**
* Keeper
* Safeguard
* Supervisor
* Defender **(4)**
* Protector
* ~~Muscle~~
* ~~Savior~~
* Bulwark 
* Tutor **(1)**
* Patron **(1)**
* Vigilant **(1)**
* Shield **(1)**
* Paladin **(1)**

Please, comment with your suggestion.

**Comment by gilvaju** [comment]
Unbroken

**Comment by andreoav** [comment]
Added synonyms

**Comment by ramon-villain** [comment]
* Tutor
* Patron
* Vigilant

**Comment by vluzrmos** [comment]
Defender ou "Artisans Defender"

**Comment by andreoav** [comment]
@vinicius73

**Comment by vinicius73** [comment]
Defender
> http://en.wikipedia.org/wiki/Defenders_(comics)

**Comment by williamoliveira** [comment]
Paladin :)

**Comment by hernandev** [comment]
Shield

**Comment by vinicius73** [comment]
I plan to migrate the [Shield](https://github.com/vinicius73/laravel-model-shield) to L5 and puts it in the Artisans.
The name of the Shield package is inspired by SHIELD Marvel.
The AMIHO showed interest in the Shield work with the "Guardian", so how about doing a tribute to our beloved Nick Fury (Colonel Nicholas Joseph "Nick" Fury)
We still have Maria Hill, Steve Rogers and Tony Stark, with these references give the following suggestions:

- Fury
- Roger
- Stark
- Hill

We can still enlarge the joke and to refer to other agencies:

- Strike
- Sword
- Armor
- Safe


http://pt.wikipedia.org/wiki/SHIELD#Outras_ag.C3.AAncias

**Comment by Fuhrmann** [comment]
Defender

**Comment by vluzrmos** [comment]
new proposals: 
* Eagle
* Hydra
